apiVersion: v2
name: mastodon
version: 0.1.0
kubeVersion: 1.26-1.28
description: "A community made Helm chart to install Mastodon in Kubernetes."
type: application
keywords:
- mastodon
- social
home: https://github.com/cloud-unpacked/mastodon-chart
sources:
- https://github.com/cloud-unpacked/mastodon-chart
- https://github.com/mastodon/mastodon
dependencies:
- name: elasticsearch
  version: 19.0.1
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: elasticsearch.enabled
- name: postgresql
  version: 11.1.3
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: postgresql.enabled
- name: redis
  version: 16.13.2
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: redis.enabled
maintainers:
- name: "Cloud Unpacked"
  email: "Ricardo@Feliciano.Tech"
  url: https://www.CloudUnpacked.com
icon: https://joinmastodon.org/_next/static/media/favicon-32x32.3a702fe9.png
appVersion: "v4.2.1"
