version: 2.1

workflows:
  main-wf:
    jobs:
    - lint

jobs:
  lint:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - run: helm lint
